FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["tidus4400.Karakuri.sln", "./"]
COPY ["src/tidus4400.Karakuri.Shared/tidus4400.Karakuri.Shared.csproj", "src/tidus4400.Karakuri.Shared/"]
COPY ["src/tidus4400.Karakuri.Web/tidus4400.Karakuri.Web.csproj", "src/tidus4400.Karakuri.Web/"]
RUN dotnet restore "src/tidus4400.Karakuri.Web/tidus4400.Karakuri.Web.csproj"

COPY . .
RUN dotnet publish "src/tidus4400.Karakuri.Web/tidus4400.Karakuri.Web.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "tidus4400.Karakuri.Web.dll"]
